export const CONVERSATIONS_DATA = [
  {
    id: "ZNG-0001",
    citizen: { name: "Ali Mammadov", initials: "AM" },
    date: "2025-01-15 14:32",
    duration: "04:25",
    category: "Case Status Inquiry",
    categoryColor: "blue",
    sentiment: 50,
    handler: "Aynur Kazimova",
    priority: "medium",
    status: "answered",
    transcript: [
      { role: "user", content: "I have a case number MU-2025/0234. I want to learn about the status of my case." },
      { role: "assistant", content: "Ali bey, one moment, let me check the system... Your case is currently under Judge Ilgar Hasanovun's proceedings." },
      { role: "user", content: "When will the next court hearing be?" },
      { role: "assistant", content: "The next hearing is scheduled for February 10, 2025, at 11:00 AM. An SMS reminder will be sent to you about the hearing." },
      { role: "user", content: "Understood, thank you." },
    ],
    aiSummary: "The citizen inquired about civil case (MU-2025/0234) regarding case progress. The case is currently under Judge Hasanov's proceedings. The next hearing is scheduled for 2025-02-10.",
    keywords: ["civil case", "case status", "judge", "in proceedings"],
    emotionScore: 50,
    operatorNotes: "Case is under Judge Ilgar Hasanov's proceedings. Next hearing scheduled for 2025-02-10.",
  },
  {
    id: "ZNG-0002",
    citizen: { name: "Leyla Hasanova", initials: "LH" },
    date: "2025-01-14 10:15",
    duration: "02:10",
    category: "Document Request",
    categoryColor: "green",
    sentiment: 60,
    handler: "AI Bot",
    priority: "low",
    status: "completed",
    transcript: [
      { role: "user", content: "I need a certified copy of the court decision from my divorce case." },
      { role: "assistant", content: "I can help you with that. Could you provide your case reference number?" },
      { role: "user", content: "It's DR-2024/1892." },
      { role: "assistant", content: "The certified copy of the decision for case DR-2024/1892 is ready for collection at the court registry office. You can collect it during working hours with a valid ID." },
    ],
    aiSummary: "Citizen requested a certified copy of a divorce case decision. Document is available for pickup at the registry with valid identification.",
    keywords: ["document request", "court decision", "certified copy", "divorce"],
    emotionScore: 65,
    operatorNotes: "",
  },
  {
    id: "ZNG-0003",
    citizen: { name: "Rashad Guliyev", initials: "RG" },
    date: "2025-01-13 16:45",
    duration: "06:30",
    category: "Complaint / Appeal",
    categoryColor: "orange",
    sentiment: 20,
    handler: "Murad Alizade",
    priority: "critical",
    status: "in review",
    transcript: [
      { role: "user", content: "I want to file a complaint about the ruling in my case. The judge was biased!" },
      { role: "assistant", content: "I understand your concern. Could you tell me your case number so I can look into the details?" },
      { role: "user", content: "Case CR-2024/0567. The ruling was completely unfair." },
      { role: "assistant", content: "I can see the case details. You have the right to file an appeal within 30 days of the ruling. Would you like me to guide you through the appeal process?" },
      { role: "user", content: "Yes, please. I want to appeal immediately." },
      { role: "assistant", content: "You'll need to submit a written appeal to the Court of Appeal. I'm transferring you to our legal guidance specialist for detailed assistance." },
    ],
    aiSummary: "Highly dissatisfied citizen wants to appeal a criminal case ruling citing judicial bias. Case has been escalated to legal guidance specialist for appeal process assistance.",
    keywords: ["complaint", "appeal", "judicial bias", "criminal case"],
    emotionScore: 20,
    operatorNotes: "Citizen is very upset. Escalated to senior legal advisor Murad Alizade for appeal guidance.",
  },
  {
    id: "ZNG-0004",
    citizen: { name: "Nigar Aliyeva", initials: "NA" },
    date: "2025-01-12 09:00",
    duration: "01:45",
    category: "Legal Consultation",
    categoryColor: "purple",
    sentiment: 85,
    handler: "AI Bot",
    priority: "low",
    status: "completed",
    transcript: [
      { role: "user", content: "Can you explain how to file a small claims case?" },
      { role: "assistant", content: "Of course! For small claims under 2000 AZN, you can file directly at the district court. You'll need to fill out Form SC-1, attach proof of the claim, and pay the filing fee of 20 AZN." },
      { role: "user", content: "Thank you, that's very helpful!" },
    ],
    aiSummary: "Citizen asked about small claims filing procedure. Provided information about form requirements, jurisdiction, and filing fees.",
    keywords: ["legal consultation", "small claims", "filing procedure"],
    emotionScore: 85,
    operatorNotes: "",
  },
  {
    id: "ZNG-0005",
    citizen: { name: "Tural Ismayilov", initials: "TI" },
    date: "2025-01-11 11:20",
    duration: "05:15",
    category: "Enforcement Inquiry",
    categoryColor: "red",
    sentiment: 30,
    handler: "Elshan Mammadli",
    priority: "high",
    status: "in review",
    transcript: [
      { role: "user", content: "The court ruled in my favor 3 months ago but the defendant still hasn't paid. What can I do?" },
      { role: "assistant", content: "I understand your frustration. Let me check the enforcement status. What's your case number?" },
      { role: "user", content: "EN-2024/3456." },
      { role: "assistant", content: "I can see the enforcement order was issued but hasn't been executed yet. I'm connecting you with the enforcement department for immediate follow-up." },
    ],
    aiSummary: "Citizen complaining about non-enforcement of a court ruling. Enforcement order exists but hasn't been executed. Escalated to enforcement department.",
    keywords: ["enforcement", "court ruling", "non-payment", "execution"],
    emotionScore: 30,
    operatorNotes: "Enforcement delay issue. Transferred to Elshan Mammadli in enforcement dept.",
  },
  {
    id: "ZNG-0006",
    citizen: { name: "Gunel Nazarova", initials: "GN" },
    date: "2025-01-10 13:50",
    duration: "03:00",
    category: "Court Hearing",
    categoryColor: "teal",
    sentiment: 75,
    handler: "AI Bot",
    priority: "low",
    status: "completed",
    transcript: [
      { role: "user", content: "I received a summons for January 20th but I have a medical appointment. Can I reschedule?" },
      { role: "assistant", content: "You can request a postponement by submitting a written request along with your medical documentation to the court at least 3 days before the hearing." },
      { role: "user", content: "Can I submit it online?" },
      { role: "assistant", content: "Yes, you can submit it through the e-court portal at courts.gov.az. You'll need your case number and registered email." },
    ],
    aiSummary: "Citizen requested information about postponing a court hearing due to medical reasons. Provided guidance on submission process via e-court portal.",
    keywords: ["court hearing", "postponement", "e-court", "scheduling"],
    emotionScore: 75,
    operatorNotes: "",
  },
  {
    id: "ZNG-0007",
    citizen: { name: "Vusal Huseynov", initials: "VH" },
    date: "2025-01-09 15:10",
    duration: "03:40",
    category: "Case Status Inquiry",
    categoryColor: "blue",
    sentiment: 55,
    handler: "Aynur Kazimova",
    priority: "medium",
    status: "answered",
    transcript: [
      { role: "user", content: "What's the status of my property dispute case PD-2024/0789?" },
      { role: "assistant", content: "Let me check that for you... The case is in the evidence review phase. The expert report is expected by January 25th." },
      { role: "user", content: "How long until the final decision?" },
      { role: "assistant", content: "Based on the current timeline, the final hearing is tentatively scheduled for mid-February. You'll receive a formal notification once the date is confirmed." },
    ],
    aiSummary: "Property dispute case inquiry. Case is in evidence review phase awaiting expert report. Final hearing expected mid-February.",
    keywords: ["property dispute", "case status", "expert report", "evidence review"],
    emotionScore: 55,
    operatorNotes: "Citizen wants updates. Expert report pending from forensics dept.",
  },
];
